spring:
  datasource:
      url: jdbc:mysql://localhost:3306/sitegroup?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: "000000"
      driver-class-name: com.mysql.jdbc.Driver

